Month7/step1
EugenyPtichkin/react-stellar-burger pull request #1
Opened 2023-09-02 04:07 UTC by EugenyPtichkin

2023-09-02 04:54 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хорошая декомпозиция компонентов
- Хорошая работа с `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Ингредиенты между булками в конструкторе должны скролиться  
- Не используйте в `ShowTab ` числительные - такая практика делает код менее понятным и усложняет расширение

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-02 04:54 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +export class BurgerConstructor extends React.Component {
**Можно лучше**
сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков

2023-09-02 04:54 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-content/burger-content.jsx
> +function CollapsableTextContent(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-09-02 11:04 UTC, EugenyPtichkin commented on src/components/burger-constructor/burger-constructor.jsx
> +export class BurgerConstructor extends React.Component {
Исправил структурные компоненты на функциональные, пойду читать, что такое хуки.

2023-09-02 11:05 UTC, EugenyPtichkin commented on src/components/burger-ingredients/burger-content/burger-content.jsx
> +function CollapsableTextContent(props) {
Сделал декомпозицию props в компоненте CollapsableTextContent

2023-09-02 11:07 UTC, EugenyPtichkin commented
Заменил числительные в компоненте ShowTab на понятные названия

2023-09-03 10:42 UTC, EugenyPtichkin commented
разобрался с использованием класса custom-scroll и применил его

2023-09-03 18:14 UTC, andryxxa93 commented
Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы.
Удачи!

2023-09-03 21:13 UTC, merged