Month9/step1
EugenyPtichkin/react-stellar-burger pull request #7
Opened 2023-12-29 12:29 UTC by EugenyPtichkin

2023-12-29 13:47 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте! C наступающим новым годом! 🎄

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/yGW8HPog9yGOKw>;

### **Сделает код лучше:**

- Чуток можно добавить отступ) <https://disk.yandex.com/i/ArZRuWFAsmkPVA>;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (или куска кода) eslint-disable-next-line. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

2023-12-29 13:47 UTC, ArslanMustafin commented on src/components/app/app.jsx
>    }, [dispatch]);
**Можно лучше:**

Можно объединить в один `useEffect`

2023-12-29 13:47 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +      const burgerIngredientsIds = [burgerIngredients.bun._id, ...burgerIngredients.ingredients.map(item => item._id)];
**Надо исправить:**

В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива
```suggestion
      const burgerIngredientsIds = [burgerIngredients.bun._id, ...burgerIngredients.ingredients.map(item => item._id), burgerIngredients.bun._id];
```

2023-12-29 13:47 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +              <BurgerContent key={dataItem._id} dataItem={dataItem} >
**Надо исправить:**

У BurgerContent не нужно указывать `key`, этот компонент не итерируется по циклу))

2023-12-29 13:47 UTC, ArslanMustafin commented on src/components/pages/profile-edit.jsx
> +  }, [dispatch]);
**Надо исправить:**

Думаю, лучше убрать отсюда получение пользователя, вы ведь уже получаете пользователя в компоненте `app`. Плюс у вас в запросах, используется проверка на истечение токена)) так что, если токен вдруг истечёт, то пользователю дадут новый, и снова сделают запрос))

2023-12-29 13:47 UTC, ArslanMustafin commented on src/utils/burger-api.js
> +const getOrderNumber = (data) => request('orders', {
**Надо исправить:**

т.к. в этот запрос нужно тоже передавать токен, то тут нужно использовать `fetchWithRefresh`

2023-12-29 17:00 UTC, EugenyPtichkin commented on src/components/app/app.jsx
>    }, [dispatch]);
Объединил. Я думал, что при объединении в один useEffect хуки dispatch будут запускаться по-очереди, а не параллельно.

2023-12-29 17:01 UTC, EugenyPtichkin commented on src/components/burger-constructor/burger-constructor.jsx
> +      const burgerIngredientsIds = [burgerIngredients.bun._id, ...burgerIngredients.ingredients.map(item => item._id)];
Сделал

2023-12-29 17:03 UTC, EugenyPtichkin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +              <BurgerContent key={dataItem._id} dataItem={dataItem} >
Выполнил. Я думал, раз идет перебор по всему массиву методом .map, то так же нужно указывать уникальный key для итерируемого компонента

2023-12-29 17:12 UTC, EugenyPtichkin commented on src/components/pages/profile-edit.jsx
> +  }, [dispatch]);
Убрал. Да, согласен, ведь в запросе updateUser, как и в getUser используется метод запроса с перезапросом токена fetchWithRefresh.

2023-12-29 17:14 UTC, EugenyPtichkin commented on src/utils/burger-api.js
> +const getOrderNumber = (data) => request('orders', {
Исправил request на fetchWithRefresh. Да, до правки в этом запросе я не передавал токен авторизации

2023-12-29 17:21 UTC, EugenyPtichkin commented
1) добавил токен авторизации в запрос POST/orders
2) добавил id булок дополнительно в конце body запроса POST/orders
3) отступ сверху модального окна добавил на окне номера заказа
4) не понял какие строки выдают предупреждения при компиляции eslint (перед которыми слеудует вставлять eslint-disable-next-line, TODO)

2023-12-30 10:58 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +      const burgerIngredientsIds = [burgerIngredients.bun._id, ...burgerIngredients.ingredients.map(item => item._id)];
Сейчас это может не критично, на на следующих этапах будет история заказав, и там вместо 2-ух булок, у вас будет заказываться 1)

2023-12-30 10:59 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

По поводу warnings - то их можно посмотреть в консоли, откуда вы запускаете приложение. <https://disk.yandex.com/i/MPQlHUv3l35Azw>

2023-12-30 11:02 UTC, ArslanMustafin commented
`> 1. добавил токен авторизации в запрос POST/orders
> 2. добавил id булок дополнительно в конце body запроса POST/orders
> 3. отступ сверху модального окна добавил на окне номера заказа
> 4. не понял какие строки выдают предупреждения при компиляции eslint (перед которыми следует вставлять eslint-disable-next-line, TODO)
>    Основые предупреждения, которые вылезают: Input element should have autocomplete... Но не указывается строка и файл, которая ему не нравится. Такое предупреждение в инете предлагают просто игнорировать.

А по поводу `Input element should have autocomplete` - https://stackoverflow.com/questions/54970352/input-elements-should-have-autocomplete-attributes. Скорее всего у инпута нету параметра autocomplete  по умолчанию) вот он и просит указать, это делать необязательно, но и лишним не будет))

2023-12-30 13:26 UTC, merged